KitTeamSe/se_api_server

src/main/java/com/se/apiserver/domain/entity/career/Career.java
=> Add Career Entity

src/main/java/com/se/apiserver/domain/entity/blacklist/Blacklist.java
=> Add add Blacklist Entity

src/main/java/com/se/apiserver/domain/entity/menu/Menu.java
=> Add Menu Entity

src/main/java/com/se/apiserver/domain/entity/board/Board.java, src/main/java/com/se/apiserver/domain/entity/board/BoardStatus.java
=> Add add Board Entity

src/main/java/com/se/apiserver/domain/entity/account/Account.java, src/main/java/com/se/apiserver/domain/entity/blacklist/Blacklist.java, src/main/java/com/se/apiserver/domain/entity/board/Board.java, src/main/java/com/se/apiserver/domain/entity/career/Career.java, src/main/java/com/se/apiserver/domain/entity/common/Anonymous.java, src/main/java/com/se/apiserver/domain/entity/employmentinfo/EmploymentInfo.java, src/main/java/com/se/apiserver/domain/entity/menu/Menu.java, src/main/java/com/se/apiserver/domain/entity/post/Post.java, src/main/java/com/se/apiserver/domain/entity/post/PostStatus.java, src/main/java/com/se/apiserver/domain/entity/post/PostType.java, src/main/java/com/se/apiserver/domain/entity/reply/Reply.java, src/main/java/com/se/apiserver/domain/entity/reply/ReplyStatus.java
=> feature relove #11 #12 #27

src/main/java/com/se/apiserver/domain/entity/authorityGroup/AuthorityGroup.java
=> Add add AuthorityGroup Entity

src/main/java/com/se/apiserver/domain/entity/authorityGroup/AuthorityGroupAccountMapping.java
=> Add AuthorityGroupAccountMapping Entity

src/main/java/com/se/apiserver/domain/entity/authorityGroup/MenuAuthorityGroupMapping.java
=> Add MenuAuthorityGroupMapping Entity

src/main/java/com/se/apiserver/domain/entity/post/Post.java, src/main/java/com/se/apiserver/domain/entity/reply/Reply.java
add validation about size
resolve : #32
=> Update Post, Reply Entity

src/main/java/com/se/apiserver/v1/tag/domain/entity/Tag.java, src/main/java/com/se/apiserver/v1/tag/domain/error/TagErrorCode.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/TagCreateUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/TagDeleteUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/TagReadUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/TagUpdateUseCase.java, src/main/java/com/se/apiserver/v1/tag/infra/api/TagApiController.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/TagCreateDto.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/TagReadDto.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/TagUpdateDto.java, src/main/java/com/se/apiserver/v1/tag/infra/repository/TagJpaRepository.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/TagCreateUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/TagDeleteUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/TagReadUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/TagUpdateUseCaseTest.java
=> Add Tag api

src/main/java/com/se/apiserver/v1/blacklist/domain/entity/Blacklist.java, src/main/java/com/se/apiserver/v1/blacklist/domain/error/BlacklistErrorCode.java, src/main/java/com/se/apiserver/v1/blacklist/domain/usecase/BlacklistCreateUseCase.java, src/main/java/com/se/apiserver/v1/blacklist/domain/usecase/BlacklistDeleteUseCase.java, src/main/java/com/se/apiserver/v1/blacklist/domain/usecase/BlacklistReadUseCase.java, src/main/java/com/se/apiserver/v1/blacklist/infra/api/BlacklistApiController.java, src/main/java/com/se/apiserver/v1/blacklist/infra/dto/BlacklistCreateDto.java, src/main/java/com/se/apiserver/v1/blacklist/infra/dto/BlacklistReadDto.java, src/main/java/com/se/apiserver/v1/blacklist/infra/repository/BlacklistJpaRepository.java, src/test/java/com/se/apiserver/v1/blacklist/domain/usecase/BlacklistCreateUseCaseTest.java, src/test/java/com/se/apiserver/v1/blacklist/domain/usecase/BlacklistDeleteUseCaseTest.java, src/test/java/com/se/apiserver/v1/blacklist/domain/usecase/BlacklistReadUseCaseTest.java
=> Add blacklist api

src/main/java/com/se/apiserver/security/service/AccountDetailService.java, src/main/java/com/se/apiserver/v1/tag/domain/entity/TagListening.java, src/main/java/com/se/apiserver/v1/tag/domain/error/TagListeningErrorCode.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagCreateUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagDeleteUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagReadUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagUpdateUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/taglistening/TagListeningCreateUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/taglistening/TagListeningDeleteUseCase.java, src/main/java/com/se/apiserver/v1/tag/domain/usecase/taglistening/TagListeningReadUseCase.java, src/main/java/com/se/apiserver/v1/tag/infra/api/TagApiController.java, src/main/java/com/se/apiserver/v1/tag/infra/api/TagListeningApiController.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/tag/TagCreateDto.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/tag/TagReadDto.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/tag/TagUpdateDto.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/taglistening/TagListeningCreateDto.java, src/main/java/com/se/apiserver/v1/tag/infra/dto/taglistening/TagListeningReadDto.java, src/main/java/com/se/apiserver/v1/tag/infra/repository/TagListeningJpaRepository.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagCreateUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagDeleteUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagReadUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/tag/TagUpdateUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/taglistening/TagListeningCreateUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/taglistening/TagListeningDeleteUseCaseTest.java, src/test/java/com/se/apiserver/v1/tag/domain/usecase/taglistening/TagListeningReadUseCaseTest.java
=> Add TagListening Api

src/main/java/com/se/apiserver/v1/lectureroom/domain/entity/LectureRoom.java, src/main/java/com/se/apiserver/v1/lectureroom/domain/error/LectureRoomErrorCode.java, src/main/java/com/se/apiserver/v1/lectureroom/domain/usecase/LectureRoomDeleteUseCase.java, src/main/java/com/se/apiserver/v1/lectureroom/domain/usecase/LectureRoomUpdateUseCase.java, src/main/java/com/se/apiserver/v1/lectureroom/infra/api/LectureRoomApiController.java, src/main/java/com/se/apiserver/v1/lectureroom/infra/dto/LectureRoomReadDto.java, src/main/java/com/se/apiserver/v1/lectureroom/infra/dto/LectureRoomUpdateDto.java, src/main/resources/init_lower.sql, src/test/java/com/se/apiserver/v1/lectureroom/domain/usecase/LectureRoomCreateUseCaseTest.java, src/test/java/com/se/apiserver/v1/lectureroom/domain/usecase/LectureRoomDeleteUseCaseTest.java, src/test/java/com/se/apiserver/v1/lectureroom/domain/usecase/LectureRoomReadUseCaseTest.java, src/test/java/com/se/apiserver/v1/lectureroom/domain/usecase/LectureRoomUpdateUseCaseTest.java
유닛 테스트만 수행해보았음.
init_lower.sql의 비밀번호 대문자 복구하였음.
=> 강의실 API 구현

src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistCreateServiceTest.java
=> Fix Blacklist service error

src/main/java/com/se/apiserver/v1/account/application/error/AccountErrorCode.java, src/main/java/com/se/apiserver/v1/common/infra/springboot/advice/GlobalControllerAdvice.java, src/main/java/com/se/apiserver/v1/common/infra/web/CorsConfig.java
=> Add CORS Config

src/main/java/com/se/apiserver/v1/common/infra/web/CorsConfig.java
=> Add cors exclude methods

src/main/java/com/se/apiserver/v1/common/infra/web/CorsHeaderFilter.java, src/main/java/com/se/apiserver/v1/menu/application/dto/MenuReadDto.java
=> Fix menu read all api's error

src/main/java/com/se/apiserver/v1/menu/application/dto/MenuReadDto.java, src/main/java/com/se/apiserver/v1/menu/application/service/MenuCreateService.java, src/main/java/com/se/apiserver/v1/menu/domain/entity/Menu.java
=> Fix menu read api spec

src/main/java/com/se/apiserver/v1/authority/infra/api/AuthorityGroupApiController.java, src/main/java/com/se/apiserver/v1/blacklist/infra/api/BlacklistApiController.java
=> Fix api's http method

src/main/java/com/se/apiserver/v1/period/application/service/PeriodUpdateService.java, src/main/java/com/se/apiserver/v1/period/infra/api/PeriodApiController.java, src/test/java/com/se/apiserver/v1/period/application/service/PeriodUpdateServiceTest.java
시간표 관련 엔티티, 교시(Period) 수정 시 Response에 pk만 반환하도록 수정.
=> 교시(Period) 수정 시 Response에 pk만 반환하도록 수정.

src/main/java/com/se/apiserver/v1/menu/application/service/MenuDeleteService.java
=> 메뉴가 삭제되지 않는 오류 픽스

src/main/java/com/se/apiserver/v1/multipartfile/application/error/MultipartFileDownloadErrorCode.java, src/main/java/com/se/apiserver/v1/multipartfile/application/error/MultipartFileUploadErrorCode.java, src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileDownloadService.java, src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileUploadService.java, src/main/java/com/se/apiserver/v1/multipartfile/infra/api/MultipartFileDownloadController.java, src/main/java/com/se/apiserver/v1/multipartfile/infra/api/MultipartFileUploadController.java, src/main/java/com/se/apiserver/v1/multipartfile/infra/config/MultipartFileProperties.java
API 서버와 파일 서버간 통신 구현
파일 업로드, 파일 다운로드 구현 완료.
#153 에서 파일 삭제 구현 진행 예정.
#152
=> F/#152 API 서버와 파일 서버간 통신 구현

src/main/java/com/se/apiserver/v1/board/infra/api/BoardApiController.java, src/main/java/com/se/apiserver/v1/common/domain/entity/Anonymous.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java, src/main/java/com/se/apiserver/v1/post/infra/dto/PostReadDto.java, src/main/java/com/se/apiserver/v1/post/infra/dto/PostUpdateDto.java, src/main/resources/init_lower.sql
게시글 목록 조회시 작성자의 닉네임과 본문 텍스트의 첫 30자를 표시하게끔 수정하였습니다.
게시글 조회 시 Paging Size는 최대 50입니다. 
Size가 51 이상으로 입력될 경우 default 값인 10으로 조회됩니다.
#155
=> F/#155 게시글 목록 조회시 닉네임 및 본문 미리보기 표시

src/main/java/com/se/apiserver/v1/common/infra/web/config/CorsHeaderProperties.java, src/main/java/com/se/apiserver/v1/common/infra/web/filter/CorsHeaderFilter.java
F/#123 사용자 및 관리자 도메인 URL을 외부에서 주입받도록 설정함.
=> F/#123 사용자 및 관리자 도메인 URL을 외부에서 주입받도록 설정

src/main/java/com/se/apiserver/v1/account/application/service/AccountContextService.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportCreateDto.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportDeleteDto.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportReadDto.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportUpdateDto.java, src/main/java/com/se/apiserver/v1/report/application/error/ReportErrorCode.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportCreateService.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportDeleteService.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportReadService.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportUpdateService.java, src/main/java/com/se/apiserver/v1/report/domain/entity/PostReport.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ProcessType.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReplyReport.java, src/main/java/com/se/apiserver/v1/report/domain/entity/Report.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportStatus.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportType.java, src/main/java/com/se/apiserver/v1/report/infra/api/ReportApiController.java, src/main/java/com/se/apiserver/v1/report/infra/repository/ReportJpaRepository.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportCreateServiceTest.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportDeleteServiceTest.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportReadServiceTest.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportUpdateServiceTest.java
=> F/#56 신고 관리 API 작성

src/main/java/com/se/apiserver/v1/account/application/service/AccountContextService.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportCreateDto.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportDeleteDto.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportReadDto.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportUpdateDto.java, src/main/java/com/se/apiserver/v1/report/application/error/ReportErrorCode.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportCreateService.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportDeleteService.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportReadService.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportUpdateService.java, src/main/java/com/se/apiserver/v1/report/domain/entity/PostReport.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ProcessType.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReplyReport.java, src/main/java/com/se/apiserver/v1/report/domain/entity/Report.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportStatus.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportType.java, src/main/java/com/se/apiserver/v1/report/infra/api/ReportApiController.java, src/main/java/com/se/apiserver/v1/report/infra/repository/ReportJpaRepository.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportCreateServiceTest.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportDeleteServiceTest.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportReadServiceTest.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportUpdateServiceTest.java
게시물-첨부파일 관련으로 롤백했을 때 신고 API가 함꼐 롤백되어서 사라졌음.
때문에 신고 API 브랜치를 복구하였음.
=> F/#56 신고 API 작성 롤백

src/main/java/com/se/apiserver/v1/common/domain/error/GlobalErrorCode.java, src/main/java/com/se/apiserver/v1/common/infra/springboot/advice/GlobalControllerAdvice.java, src/main/java/com/se/apiserver/v1/post/application/dto/PostReadDto.java, src/main/java/com/se/apiserver/v1/post/application/error/PostSearchErrorCode.java, src/main/java/com/se/apiserver/v1/post/application/service/PostCreateService.java, src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java, src/main/java/com/se/apiserver/v1/post/domain/entity/PostSearchType.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java, src/main/java/com/se/apiserver/v1/post/infra/repository/PostQueryRepository.java, src/main/java/com/se/apiserver/v1/post/infra/repository/PostQueryRepositoryImpl.java
- 게시글 검색 API 작성 완료
- 게시글 API 컨트롤러의 작성/수정에서 첨부파일 파라미터 제외
- Global Controller Advice에 ENUM 입력 에러 추가
=> F/#51 게시글 검색 API 작성

src/main/java/com/se/apiserver/v1/attach/application/service/AttachCreateService.java, src/main/java/com/se/apiserver/v1/multipartfile/application/dto/MultipartFileUploadDto.java, src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileUploadService.java
MultipartFileUploadDto 추가, Upload Service에 반영
=> F/#190 MultipartFileUploadDto 추가, Upload Service에 반영

Dockerfile
=> F/#194 도커파일에 타임존 설정 추가

src/main/java/com/se/apiserver/v1/common/infra/dto/ErrorResponse.java, src/main/java/com/se/apiserver/v1/common/infra/dto/SuccessResponse.java
#196 
두 클래스는 다음과 같은 변수를 가지게 통일 하였음.
- int status : HTTP 상태
- String code : 동작 제어를 위한 식별자
=> F/#196 ErrorCode 및 SuccessResponse 변수 통일화

src/main/java/com/se/apiserver/v1/report/application/dto/ReportReadDto.java, src/main/java/com/se/apiserver/v1/report/application/dto/ReportUpdateDto.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportUpdateService.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportStatus.java
수정하는 계정의 ID를 ProcessorId로 설정하게 하였음.
신고 조회 DTO에서 닉네임 변수를 id로 변경.
ReportStatus의 승인(Accepted)를 처리됨(Processed)로 변경
=> F/#198 신고 수정 DTO에서 ProcessorId 제외.

src/main/java/com/se/apiserver/v1/report/application/dto/ReportUpdateDto.java
Report Update DTO의 status 예제 수정.
=> F/#198 Report Update DTO의 status 예제 수정.

src/main/java/com/se/apiserver/v1/tag/application/service/TagReadService.java
익명 사용자는 문자열 태그 검색을 사용할 수 없게 하였음.
=> F/#202 익명 사용자 태그 문자열 검색 제한

src/main/java/com/se/apiserver/v1/account/infra/api/AccountApiController.java
회원 정보 조회 시 조회된 결과를 반환하도록 수정.
기존 코드는 조회 결과를 반환하지 않고 있었음.
=> F/#210 회원 정보 조회 시 조회된 결과를 반환하도록 수정.

src/main/java/com/se/apiserver/v1/account/application/service/AccountContextService.java, src/main/java/com/se/apiserver/v1/account/application/service/AccountSignInService.java, src/main/java/com/se/apiserver/v1/account/domain/entity/Account.java, src/main/java/com/se/apiserver/v1/account/infra/api/AccountApiController.java, src/main/java/com/se/apiserver/v1/common/infra/security/filter/IpBlacklistFilters.java
- IP 획득 메소드 변경 : 헤더에서 X-Forwarded-For 추출하여 IP 저장.
- 사용자 로그인 시 최종 로그인 IP 갱신
=> F/#212 IP 획득 메소드 변경

src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java
=> F/#216 익명 사용자 게시글 조회 핫픽스

src/main/java/com/se/apiserver/v1/account/application/service/AccountReadService.java, src/main/java/com/se/apiserver/v1/account/infra/api/AccountApiController.java
로그인을 한 사용자는 이 기능으로 자신의 사용자 정보를 조회할 수 있습니다.
=> F/#238 사용자 관리 API에 내 회원 정보 조회 기능 추가

src/main/java/com/se/apiserver/v1/account/application/service/AccountSignInService.java, src/main/java/com/se/apiserver/v1/account/infra/api/AccountApiController.java, src/main/java/com/se/apiserver/v1/authority/application/error/AuthorityGroupErrorCode.java, src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupReadService.java, src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroupaccountmapping/AuthorityGroupAccountMappingReadService.java, src/main/java/com/se/apiserver/v1/authority/infra/repository/AuthorityGroupAccountMappingJpaRepository.java
- 관리자인지 아닌지 판단은 소속된 그룹 중 SYSTEM 타입의 그룹이 있으면 관리자로 판단.
- 권한 쪽 서비스(AuthorityGroupRead, AuthorityGroupAccountMappingRead) 및 JpaRepository 수정됨
=> F/#236 사용자 관리 API에 관리자 전용 로그인 기능 추가

src/main/java/com/se/apiserver/v1/tag/domain/entity/Tag.java
=> F/#244 Tag text 컬럼 columnDefinition 롤백

src/main/java/com/se/apiserver/v1/taglistening/application/service/TagListeningReadService.java, src/main/java/com/se/apiserver/v1/taglistening/infra/api/TagListeningApiController.java
- 사용자 아이디로 수신 목록 조회 권한 변경(TAG_ACCESS 제외)
- 수신 태그 API ResponseStatus 오타 수정
=> F/#248 내 수신 태그 목록 조회 추가

src/main/java/com/se/apiserver/v1/account/application/service/AccountContextService.java, src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java, src/main/java/com/se/apiserver/v1/post/application/service/PostUpdateService.java, src/main/java/com/se/apiserver/v1/post/domain/entity/Post.java
=> Update post read service

src/main/java/com/se/apiserver/v1/tag/infra/api/TagApiController.java
- 로그인 사용자도 태그 전체 조회/조회 가능하도록 하였음.
=> F/#256 로그인 사용자도 태그 전체 조회/조회 가능하도록 하였음.

src/main/java/com/se/apiserver/v1/authority/application/dto/authoritygroup/AuthorityGroupReadDto.java, src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupCreateService.java, src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupReadService.java, src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupUpdateService.java, src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroupauthoritymapping/AuthorityGroupAuthorityMappingReadService.java, src/main/java/com/se/apiserver/v1/authority/infra/api/AuthorityGroupApiController.java, src/main/java/com/se/apiserver/v1/authority/infra/repository/AuthorityGroupAuthorityMappingJpaRepository.java
- 권한 그룹을 목록으로 조회할때는 소유 권한 목록을 보여주지 않음.
- 권한 그룹 API에서 Create, Update 시 반환을 Long pk로 하도록 변경함.
=> F/#255 권한 그룹을 pk로 조회하면 그 그룹이 가진 권한을 함께 반환하도록 하였음.

src/main/java/com/se/apiserver/v1/board/application/service/BoardAuthorityService.java, src/main/java/com/se/apiserver/v1/board/infra/api/BoardApiController.java
=> F/#254 게시판 접근/관리 권한 검증 API 작성

src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java
게시글 id를 주면 본인이 쓴 게시글인지, 관리자인지 검사함
- 익명 게시글인 경우에는 비밀이 아니면 OK, 비밀글인 경우 실패함.
=> F/#262 게시글 관리 권한 확인 API 추가

src/main/java/com/se/apiserver/v1/post/application/dto/PostReadDto.java
로그인 사용자의 비밀 게시글 조회 시 본인/관리자가 아니면 예외 발생하게 하였음.
=> F/#268 로그인 사용자의 비밀 게시글 조회 시 본인/관리자가 아니면 예외 발생하게 하였음.

src/main/java/com/se/apiserver/v1/account/application/dto/QuestionReadDto.java, src/main/java/com/se/apiserver/v1/account/application/service/QuestionReadService.java, src/main/java/com/se/apiserver/v1/account/infra/api/AccountApiController.java
=> F/#270 회원가입 질문 목록 조회 API 작성

src/main/java/com/se/apiserver/v1/menu/application/error/MenuErrorCode.java, src/main/java/com/se/apiserver/v1/menu/application/service/MenuCreateService.java
Type이 Board 인 메뉴는 게시판 생성으로만 만들 수 있도록 하였음.
=> F/#273 메뉴 생성 시 Type이 Board 인 경우 생성할 수 없도록 하였음.

src/main/java/com/se/apiserver/v1/board/domain/entity/Board.java, src/main/java/com/se/apiserver/v1/menu/application/dto/MenuCreateDto.java, src/main/java/com/se/apiserver/v1/menu/application/dto/MenuReadDto.java, src/main/java/com/se/apiserver/v1/menu/application/dto/MenuUpdateDto.java, src/main/java/com/se/apiserver/v1/menu/domain/entity/Menu.java, src/main/java/com/se/apiserver/v1/menu/infra/api/MenuApiController.java
- 메뉴 Read DTO에 boardId 추가
- 메뉴 Create, Update DTO 일부 제약조건 삭제
- 메뉴 API 컨트롤러 오타 수정
=> F/#281 Board-Menu 양방향 매핑화

src/main/java/com/se/apiserver/v1/account/application/dto/AccountReadDto.java, src/main/java/com/se/apiserver/v1/account/application/dto/QuestionReadDto.java, src/main/java/com/se/apiserver/v1/account/application/service/QuestionReadService.java, src/main/java/com/se/apiserver/v1/account/infra/api/AccountApiController.java
@gilmujjang 요청 이슈입니다.
현재 회원정보 수정을 할 때 본인이 회원가입했을 때 사용한 질문과, 답변을 알 수 없는 문제가 있습니다.
사용자 정보를 읽을때 합법적인 접근(Legal Access)인 경우 질문 번호(QuestionId)와 답변(answer)를 함께 반환하도록 변경하였습니다.
=> [KIT-97] 내 질문 및 답변 조회 기능 추가

src/main/java/com/se/apiserver/v1/account/application/service/AccountCreateService.java, src/test/java/com/se/apiserver/v1/account/application/service/AccountCreateServiceTest.java
회원 가입 서비스(AccountCreateService) Mockito 이용하여 단위테스트 작성하였습니다.
=> [KIT-70] 회원 가입 서비스 단위테스트 

src/main/java/com/se/apiserver/v1/account/application/dto/AccountUpdateDto.java, src/main/java/com/se/apiserver/v1/account/application/service/AccountUpdateService.java
- 회원 정보 수정 DTO에서 학번을 제외하였습니다.
- 회원 정보 수정 로직 중, 닉네임 중복 검사 시 본인 닉네임을 그대로 사용하는 경우 중복 예외를 발생시키지 않게 하였습니다.
=> [KIT-113] 회원 정보 수정 DTO 및 서비스 수정

src/test/java/com/se/apiserver/v1/account/application/service/AccountDeleteServiceTest.java
=> [KIT-70] 회원 삭제 서비스 단위테스트

src/test/java/com/se/apiserver/v1/account/application/service/AccountFindIdServiceTest.java
=> [KIT-70] 회원 검색(byEmail) 서비스 단위테스트

src/test/java/com/se/apiserver/v1/account/application/service/AccountFindPasswordServiceTest.java
=>  [KIT-70] 회원 비밀번호 찾기 서비스 단위테스트

src/test/java/com/se/apiserver/v1/account/application/service/AccountReadServiceTest.java
=> [KIT-70] 회원 읽기/검색 서비스 단위테스트

src/test/java/com/se/apiserver/v1/account/application/service/AccountSignInServiceTest.java
=> [KIT-70] 회원 로그인 서비스 단위테스트

src/test/java/com/se/apiserver/v1/account/application/service/QuestionReadServiceTest.java
=> Test: QuestionReadService Test 추가

src/test/java/com/se/apiserver/v1/account/application/service/AccountContextServiceTest.java
=> [KIT-70] AccountContextService 단위테스트

src/test/java/com/se/apiserver/v1/account/domain/entity/AccountTest.java
- Account Entity의 제약조건 및 기타 Method에 대한 테스트 추가
=> [KIT-70] 회원 Entity 단위테스트

src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyCreateDto.java
=> [KIT-120] AttachDto 수정

src/test/java/com/se/apiserver/v1/authority/application/service/authority/AuthorityReadServiceTest.java
=> [KIT-68] 권한 읽기 서비스 단위테스트

src/main/java/com/se/apiserver/v1/post/application/dto/PostCreateDto.java, src/main/java/com/se/apiserver/v1/post/application/service/PostCreateService.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java
=> [KIT-119] 게시글 테스트 작성 및 트러블슈팅 / 게시글 생성 로직 수정

src/test/java/com/se/apiserver/v1/board/application/service/BoardCreateServiceTest.java
- Major Reviewer: @KitTeamSe/be
게시판 create service 유닛 테스트
case 1 : board 생성 성공
case 2 : board 생성 실패, 한글 이름 존재
case 3 : board 생성 실패, 영어 이름 존재
case 4 : board 생성 실패, 권한에 동일 한글 이름 존재
case 5 : board 생성 실패, 권한에 동일 영어 이름 존재
case 6 : board 생성 실패, 메뉴에 동일 한글 이름 존재
case 7 : board 생성 실패, 메뉴에 동일 영어 이름 존재
case 8 : board 생성 실패, 메뉴 URL에 동일 영어 이름 존재
=> [KIT-121] 게시판-테스트-작성-및-트러블슈팅 / add board create service test

src/main/java/com/se/apiserver/v1/reply/application/service/ReplyDeleteService.java, src/test/java/com/se/apiserver/v1/reply/application/service/ReplyDeleteServiceTest.java
- 댓글 삭제 Unit Test
- 조건문 추가
- 로그인 안한 사용자가 일반 댓글 삭제 요청 시 예외 발생
=> [KIT-120] 댓글 테스트 작성 및 트러블 슈팅 / 댓글 삭제 Unit Test

src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyReadDto.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyReadService.java, src/main/java/com/se/apiserver/v1/reply/domain/entity/Reply.java, src/test/java/com/se/apiserver/v1/reply/application/service/ReplyReadServiceTest.java
- 댓글 단일 조회 테스트
- 비밀 댓글 조회 관련 로직 추가
- 비밀 댓글은 작성자 본인, 관리자, 게시글 작성자만 조회 가능
- 나머지 사용자는 비밀 댓글 내용 조회 불가능
=> [KIT-120] 댓글 테스트 작성 및 트러블 슈팅 / 댓글 단일 조회 테스트 및 로직 추가

src/main/java/com/se/apiserver/v1/reply/domain/entity/Reply.java
- Reply Entity 내에서 사용된 Error Code 수정
=> [KIT-120] ReplyErrorCode 수정

src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyReadDto.java, src/main/java/com/se/apiserver/v1/reply/application/dto/request/ReplyPaginationRequest.java, src/main/java/com/se/apiserver/v1/reply/application/error/ReplyErrorCode.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyReadService.java, src/main/java/com/se/apiserver/v1/reply/domain/entity/Reply.java, src/main/java/com/se/apiserver/v1/reply/infra/api/ReplyApiController.java, src/main/java/com/se/apiserver/v1/reply/infra/repository/ReplyJpaRepository.java
=> [KIT-120] 댓글 테스트 작성 및 트러블 슈팅 / 댓글 리스트 및 익명 댓글 조회

src/test/java/com/se/apiserver/v1/reply/application/service/ReplyCreateServiceTest.java
=> [KIT-120] 댓글 테스트 작성 및 트러블 슈팅 / 댓글 등록 Unit Test

src/test/java/com/se/apiserver/v1/reply/application/service/ReplyUpdateServiceTest.java
=> [KIT-120] 댓글 테스트 작성 및 트러블 슈팅 / 댓글 수정 Unit Test 

src/main/java/com/se/apiserver/v1/attach/application/service/AttachCreateService.java, src/main/java/com/se/apiserver/v1/attach/application/service/AttachDeleteService.java, src/main/java/com/se/apiserver/v1/attach/infra/repository/AttachJpaRepository.java, src/main/java/com/se/apiserver/v1/post/application/dto/PostUpdateDto.java, src/main/java/com/se/apiserver/v1/post/application/service/PostUpdateService.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java
- 첨부 파일 일괄 삭제 변경
- AttachId 리스트 이용 -> postId or replyId 이용
- 게시글 수정 Service 수정
=> [KIT-119] 게시글 테스트 작성 및 트러블슈팅 / update-post

src/main/java/com/se/apiserver/v1/menu/application/dto/MenuCreateDto.java, src/main/java/com/se/apiserver/v1/menu/application/dto/MenuUpdateDto.java, src/main/java/com/se/apiserver/v1/menu/application/service/MenuCreateService.java, src/main/java/com/se/apiserver/v1/menu/application/service/MenuUpdateService.java, src/main/java/com/se/apiserver/v1/menu/domain/entity/Menu.java, src/main/java/com/se/apiserver/v1/tag/domain/entity/Tag.java, src/test/java/com/se/apiserver/v1/menu/application/service/MenuCreateServiceTest.java, src/test/java/com/se/apiserver/v1/menu/application/service/MenuUpdateServiceTest.java
- menu create test
- menu update test
- @Data @AllArgsConstructor 삭제
-  resolve : #280 메뉴 수정 시 url 빈 값으로 받을 수 있게 수정
- Tag 테이블 생성가능하도록 제약조건 삭제 (추후 재수정 가능)
=> [KIT-118] menu create & update test 및 트러블슈팅

src/main/java/com/se/apiserver/v1/menu/application/dto/MenuReadDto.java, src/main/java/com/se/apiserver/v1/menu/application/service/MenuDeleteService.java, src/main/java/com/se/apiserver/v1/menu/application/service/MenuReadService.java, src/test/java/com/se/apiserver/v1/menu/application/service/MenuDeleteServiceTest.java, src/test/java/com/se/apiserver/v1/menu/application/service/MenuReadServiceTest.java
- 테스트코드 외 다른 클래스들의 수정사항은 생성자, 코드스타일밖에 없습니다
=> [KIT-118] menu read & delete test 작성 및 트러블슈팅

src/main/java/com/se/apiserver/v1/common/infra/resttemplate/config/RestTemplateConfig.java, src/main/java/com/se/apiserver/v1/common/presentation/response/Response.java, src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileService.java
- Response NoArgsConstructor 추가
- MultipartFileService의 service명 받아올 수 있도록 @value 이용하여 SERVICE_NAME추가
- 기존 new 이용한 RestTemplate을 Bean으로 관리하도록 Config 추가(세부 설정은 추가 논의 필요)
=> [KIT-122] multipartfile setting

src/main/java/com/se/apiserver/v1/multipartfile/application/dto/MultipartFileUploadDto.java, src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileUploadService.java, src/test/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileUploadServiceTest.java
- file server의 반환형을 고려하여 dto 축소
- restTemplate 의존성 주입받는 형식으로 변경
- 제한적으로 반환되는 정보(downloadUrl) 고려하여 일부 로직 변경
- 단일/다중 별로 구분되어 있던 메소드 통일
=> [KIT-122] 파일 업로드 서비스 기능 수정 및 단위 테스트 작성

src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileDownloadService.java, src/test/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileDownloadServiceTest.java
- restTemplate 의존성 주입받아 사용
- file server의 path Variable의 query string으로 변경될 것을 고려하여 UriComponentsBuilder 사용
=> [KIT-122] 파일 다운로드 서비스 기능 수정 및 단위 테스트

src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileDeleteService.java, src/test/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileDeleteServiceTest.java
- restTemplate 의존성 주입받아 사용
- file server의 path Variable의 query string으로 변경될 것을 고려하여 UriComponentsBuilder 사용
=> [KIT-122] 파일 삭제 서비스 기능 수정 및 단위 테스트

src/main/java/com/se/apiserver/v1/board/application/service/BoardReadService.java, src/test/java/com/se/apiserver/v1/board/application/service/BoardReadServiceTest.java
- Major Reviewer: @KitTeamSe/be
게시판 Read service 유닛 테스트
case 1 : board 조회 성공
case 2 : board 조회 전부 성공
case 3 : board 조회 실패, 존재하지 않는 board
=> [KIT-121] 게시판 테스트 작성 및 트러블슈팅 / add read test service test

src/test/java/com/se/apiserver/v1/board/application/service/BoardUpdateServiceTest.java
- Major Reviewer: @KitTeamSe/be
게시판 Update service 유닛 테스트
case 1 : board 수정 성공
case 2 : board 수정 실패, 존재하지 않는 board
case 3 : board 수정 실패, 한글 이름 존재
case 4 : board 수정 실패, 영어 이름 존재
case 5 : board 수정 실패, 권한에 동일 한글 이름 존재
case 6 : board 수정 실패, 권한에 동일 영어 이름 존재
case 7 : board 수정 실패, 메뉴에 동일 한글 이름 존재
case 8 : board 수정 실패, 메뉴에 동일 영어 이름 존재
case 9 : board 수정 실패, 메뉴 URL에 동일 영어 이름 존재
=> [KIT-121] 게시판 테스트 작성 및 트러블슈팅 / add update service test

src/main/java/com/se/apiserver/v1/board/application/service/BoardDeleteService.java, src/main/java/com/se/apiserver/v1/post/domain/entity/Post.java, src/main/java/com/se/apiserver/v1/post/infra/repository/PostJpaRepository.java, src/test/java/com/se/apiserver/v1/board/application/service/BoardDeleteServiceTest.java
게시판 삭제하기 전에 게시글 삭제 하는 기능 및 테스트 추가했습니다.
삭제된 게시글은 임의로 deletedBoard라는 게시판으로 이동합니다.
(Not Null이여서 만든 게시판)
=> [KIT-121] 게시판 테스트 작성 및 트러블 슈팅 /delete post before deleting board

src/test/java/com/se/apiserver/v1/board/application/service/BoardAuthorityServiceTest.java
=> [KIT-121] 게시판 테스트 작성 및 트러블 슈팅 / add board authority service test

src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupDeleteService.java, src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupDeleteServiceTest.java
- service 반환 형 수정: boolean -> void
- unit test
=> [KIT-68] 권한그룹 삭제 서비스 단위 테스트 추가

src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java, src/main/java/com/se/apiserver/v1/post/infra/repository/PostQueryRepositoryImpl.java, src/test/java/com/se/apiserver/v1/post/application/service/PostReadServiceTest.java
=> [KIT-119] 게시글 테스트 작성 및 트러블 슈팅 / 게시글 조회 Unit Test

src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileService.java
=> [KIT-122] Multipart file 서비스 내 annotation 수정

src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupReadServiceTest.java
- AuthorityGroupReadService unit test 추가
=> [KIT-68] 권한그룹 읽기 서비스 단위 테스트 추가

src/main/java/com/se/apiserver/v1/reply/application/error/ReplyErrorCode.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyCreateService.java, src/test/java/com/se/apiserver/v1/reply/application/service/ReplyCreateServiceTest.java
=> [KIT-147] 댓글 대댓글까지만 지원하도록 수정

src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyReadDto.java
=> [KIT-120] 댓글 조회 DTO에 작성일시 추가

src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroup/AuthorityGroupUpdateServiceTest.java
- AuthorityGroupUpdateService unit test 추가
=> [KIT-122] 권한그룹 수정 서비스 단위 테스트 추가

src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroupaccountmapping/AuthorityGroupAccountMappingCreateServiceTest.java
- AuthorityGroupAccountMappingCreateService unit test 추가
=> [KIT-68] 권한그룹 계정 Mapping 생성 서비스 단위 테스트 추가

build.gradle, src/main/java/com/se/apiserver/v1/attach/application/service/AttachCreateService.java, src/main/java/com/se/apiserver/v1/attach/infra/api/AttachApiController.java, src/main/java/com/se/apiserver/v1/post/application/service/PostCreateService.java, src/main/java/com/se/apiserver/v1/post/application/service/PostUpdateService.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyCreateService.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyUpdateService.java, src/test/java/com/se/apiserver/v1/attach/application/service/AttachCreateServiceTest.java, src/test/java/com/se/apiserver/v1/post/application/service/PostCreateServiceTest.java, src/test/java/com/se/apiserver/v1/reply/application/service/ReplyCreateServiceTest.java, src/test/java/com/se/apiserver/v1/reply/application/service/ReplyUpdateServiceTest.java
- AttachCreateService 리팩토링
- Unit Test
=> [KIT-155] 첨부파일 테스트 작성 및 트러블슈팅 / Attach Create

src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroupaccountmapping/AuthorityGroupAccountMappingReadServiceTest.java
- AuthorityGroupAccountMappingReadService unit test 추가
=> [KIT-68] 권한그룹 계정 Mapping 읽기 서비스 단위 테스트

src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroupauthoritymapping/AuthorityGroupAuthorityMappingCreateServiceTest.java
- AuthorityGroupAuthorityMappingCreateService unit test 추가
=> [KIT-68] 권한그룹 권한 Mapping 생성 서비스 단위 테스트

src/main/java/com/se/apiserver/v1/authority/application/service/authoritygroupauthoritymapping/AuthorityGroupAuthorityMappingDeleteService.java, src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroupauthoritymapping/AuthorityGroupAuthorityMappingDeleteServiceTest.java
- 반환형 수정 : boolean -> void
- unit test 추가
=> [KIT-68] 권한그룹 권한 Mapping 삭제 서비스 단위 테스트

src/test/java/com/se/apiserver/v1/authority/application/service/authoritygroupauthoritymapping/AuthorityGroupAuthorityMappingReadServiceTest.java
- AuthorityGroupAuthorityMappingReadService unit test 추가
=> [KIT-68] 권한그룹 권한 Mapping 읽기 서비스 단위 테스트

src/test/java/com/se/apiserver/v1/authority/domain/entity/AuthorityGroupTest.java, src/test/java/com/se/apiserver/v1/authority/domain/entity/AuthorityTest.java
- 제약조건 검사 및 부가 메소드에 대한 unit test
=> [KIT-68] Authority, AuthorityGroup 단위 테스트

src/main/java/com/se/apiserver/v1/report/application/dto/ReportCreateDto.java, src/main/java/com/se/apiserver/v1/report/application/error/ReportErrorCode.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportCreateService.java, src/main/java/com/se/apiserver/v1/report/domain/entity/Report.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportResult.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportStatus.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportCreateServiceTest.java
=> [KIT-148] 신고 create service 트러블슈팅 및 테스트코드 작성

src/main/resources/logback-spring.xml
로그 프로필을 배포, stacktrace, debug 3가지 프로필로 분리했습니다.
=> [KIT-114] 로그 프로필 세분화

src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistCreateServiceTest.java
- BlacklistCreateService unit test 추가
=> [KIT-159] 블랙리스트 생성 서비스 단위 테스트 작성

src/main/java/com/se/apiserver/v1/blacklist/application/service/BlacklistCreateService.java, src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistDeleteServiceTest.java
- BlacklistDeleteService unit test 추가
- CreateService 반환형 수정 ( 실수로 Delete 브랜치에 커밋했습니다. 내용이 많지 않으니 양해바랍니다 )
=> [KIT-159] 블랙리스트 삭제 서비스 단위 테스트 작성

src/main/java/com/se/apiserver/v1/blacklist/application/service/BlacklistDetailService.java, src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistDetailServiceTest.java
- isBaned 로직 수정
- BlacklistDetailService unit test 추가
=> [KIT-159] 블랙리스트 디테일 서비스 단위 테스트 작성

src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistReadServiceTest.java
- BlacklistReadService unit test 추가
=> [KIT-159] 블랙리스트 조회 서비스 단위 테스트 작성 

src/main/java/com/se/apiserver/v1/blacklist/application/dto/BlacklistCreateDto.java, src/main/java/com/se/apiserver/v1/blacklist/application/dto/BlacklistReadDto.java
- @Data -> @Getter
- @AllArgs 삭제
=> [KIT-159] 블랙리스트 DTO lombok 수정

src/test/java/com/se/apiserver/v1/blacklist/domain/entity/BlacklistTest.java
=> [KIT-159] 블랙리스트 엔티티 단위 테스트 작성 

src/main/java/com/se/apiserver/v1/reply/application/error/ReplyErrorCode.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyCreateService.java
=> [KIT-160] 삭제된 댓글에 대댓글을 달 수 없게 수정

src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java, src/main/java/com/se/apiserver/v1/reply/infra/api/ReplyApiController.java
DeleteMapping 중 body를 사용하는 요청은 PostMapping으로 수정함.
=> [KIT-161] DeleteMapping 중 body를 사용하는 요청은 PostMapping으로 수정함.

src/main/java/com/se/apiserver/v1/report/application/service/ReportDeleteService.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportDeleteServiceTest.java
- 신고 delete 테스트코드 작성
- @AllArgs어노테이션 삭제에 따른 생성자 추가
=> [KIT-148] 신고 DELETE 테스트코드 작성

src/main/java/com/se/apiserver/v1/post/application/service/PostCreateService.java, src/main/java/com/se/apiserver/v1/post/application/service/PostUpdateService.java, src/main/java/com/se/apiserver/v1/tag/application/error/TagErrorCode.java, src/test/java/com/se/apiserver/v1/post/application/service/PostCreateServiceTest.java, src/test/java/com/se/apiserver/v1/post/application/service/PostUpdateServiceTest.java
- 게시글 등록, 수정 시 태그 개수체크
- Unit Test 추가
=> [KIT-149] 태그 도메인 리메이크 / 게시글 내 태그 개수 제한

src/main/java/com/se/apiserver/v1/post/domain/entity/Post.java
=> [KIT-13] 게시물 numReply 갱신

src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyReadDto.java
- 댓글 조회 DTO에 parentId 추가.
- 댓글 조회 DTO의 본문을 채우는 부분을 따로 함수로 뺐음.
=> [KIT-166] 댓글 조회 시 parentId 포함

src/main/java/com/se/apiserver/v1/report/application/dto/ReportUpdateDto.java, src/main/java/com/se/apiserver/v1/report/application/error/ReportErrorCode.java, src/main/java/com/se/apiserver/v1/report/application/service/ReportUpdateService.java, src/main/java/com/se/apiserver/v1/report/domain/entity/Report.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportResult.java, src/main/java/com/se/apiserver/v1/report/domain/entity/ReportStatus.java, src/main/java/com/se/apiserver/v1/report/infra/api/ReportApiController.java, src/test/java/com/se/apiserver/v1/report/application/service/ReportUpdateServiceTest.java
- Controller 명칭 변경 : 신고 수정 -> 신고 처리
- ReportStatus는 관리자가 임의적으로 수정할 수 없음. 대신 ReportResult를 관리자가 수정하게끔 하고, ReportStatus는 내부적으로 값이 바뀌게끔 처리
- +) 테스트코드 작성 및 Dto에 NotNull 추가
=> [KIT-148] 신고 UPDATE service 트러블슈팅 및 테스트코드 작성

src/main/java/com/se/apiserver/v1/common/domain/exception/PermissionDeniedException.java, src/main/java/com/se/apiserver/v1/common/domain/exception/UniqueValueAlreadyExistsException.java, src/main/java/com/se/apiserver/v1/tag/application/dto/TagCreateDto.java, src/main/java/com/se/apiserver/v1/tag/application/service/TagCreateService.java, src/main/java/com/se/apiserver/v1/tag/domain/entity/Tag.java, src/test/java/com/se/apiserver/v1/tag/application/service/TagCreateServiceTest.java
=> [KIT-149] 태그 도메인 리메이크 / Tag Create

src/main/java/com/se/apiserver/v1/post/application/dto/PostReadDto.java
=> [KIT-168] 게시글 조회 결과에 작성자 id 추가

src/main/java/com/se/apiserver/v1/post/domain/entity/Post.java, src/main/java/com/se/apiserver/v1/tag/application/service/TagDeleteService.java, src/main/java/com/se/apiserver/v1/tag/domain/entity/Tag.java, src/main/java/com/se/apiserver/v1/taglistening/infra/repository/TagListeningJpaRepository.java, src/test/java/com/se/apiserver/v1/tag/application/service/TagDeleteServiceTest.java
- Post - Tag 간 양방향 매핑 관계 수정
- Tag 삭제 시 post_tag 테이블에서 관련 Tag를 가진 데이터 삭제
- Tag 삭제 단위 테스트
=> [KIT-149] 태그 도메인 리메이크 / Tag Delete Unit Test

src/main/java/com/se/apiserver/v1/post/application/dto/PostReadDto.java
=> [KIT-168] nickname으로 인해 발생한 오류 해결

src/main/java/com/se/apiserver/v1/common/domain/exception/UnauthenticatedException.java, src/main/java/com/se/apiserver/v1/common/domain/exception/UniqueValueAlreadyExistsException.java, src/main/java/com/se/apiserver/v1/taglistening/application/dto/TagListeningCreateDto.java, src/main/java/com/se/apiserver/v1/taglistening/application/service/TagListeningCreateService.java, src/main/java/com/se/apiserver/v1/taglistening/domain/entity/TagListening.java, src/test/java/com/se/apiserver/v1/taglistening/application/service/TagListeningCreateServiceTest.java
=> [KIT-149] 태그 도메인 리메이크 / 수신 태그 등록 Unit Test

src/main/java/com/se/apiserver/v1/account/application/service/AccountContextService.java, src/main/java/com/se/apiserver/v1/taglistening/application/service/TagListeningDeleteService.java, src/test/java/com/se/apiserver/v1/taglistening/application/service/TagListeningDeleteServiceTest.java
=> [KIT-149] 태그 도메인 리메이크 / 수신 태그 삭제 Unit Test

src/main/java/com/se/apiserver/v1/taglistening/application/dto/TagListeningReadDto.java, src/main/java/com/se/apiserver/v1/taglistening/application/service/TagListeningReadService.java, src/main/java/com/se/apiserver/v1/taglistening/infra/api/TagListeningApiController.java, src/test/java/com/se/apiserver/v1/taglistening/application/service/TagListeningReadServiceTest.java
- Lombok 제거
- 수신 태그 조회 Unit Test
=> [KIT-149] 태그 도메인 리메이크 / 수신 태그 조회 Unit Test

src/main/java/com/se/apiserver/v1/menu/application/dto/MenuCreateDto.java, src/main/java/com/se/apiserver/v1/menu/application/dto/MenuReadDto.java, src/main/java/com/se/apiserver/v1/menu/application/dto/MenuUpdateDto.java, src/main/java/com/se/apiserver/v1/menu/application/service/MenuUpdateService.java, src/main/java/com/se/apiserver/v1/menu/domain/entity/Menu.java, src/test/java/com/se/apiserver/v1/menu/application/service/MenuUpdateServiceTest.java
- resolve : #283 
- create, update 제약조건 수정
- read시 생성일시, 수정일시 추가
- DTO 제약조건 및 서비스 로직 변경에 따른 test코드 수정.
=> [KIT-167] 메뉴 DTO 제약조건 변경에 따른 service, test 수정

src/main/java/com/se/apiserver/v1/post/application/dto/PostCreateDto.java, src/main/java/com/se/apiserver/v1/post/application/dto/PostUpdateDto.java, src/main/java/com/se/apiserver/v1/post/application/service/PostCreateService.java, src/main/java/com/se/apiserver/v1/post/application/service/PostUpdateService.java, src/main/java/com/se/apiserver/v1/post/domain/entity/Post.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java, src/test/java/com/se/apiserver/v1/post/application/service/PostCreateServiceTest.java, src/test/java/com/se/apiserver/v1/post/application/service/PostUpdateServiceTest.java
- 게시글 Create 및 Update 시 첨부 파일 관련 로직 제거
- 게시글 Create 및 Update Unit Test 수정
=> [KIT-178] 첨부 파일 관련 로직 분리 / 게시글 Create 및 Update 수정

src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyCreateDto.java, src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyUpdateDto.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyCreateService.java, src/main/java/com/se/apiserver/v1/reply/application/service/ReplyUpdateService.java, src/main/java/com/se/apiserver/v1/reply/domain/entity/Reply.java, src/main/java/com/se/apiserver/v1/reply/infra/api/ReplyApiController.java, src/test/java/com/se/apiserver/v1/reply/application/service/ReplyCreateServiceTest.java, src/test/java/com/se/apiserver/v1/reply/application/service/ReplyUpdateServiceTest.java
- 댓글 Create 및 Update 시 첨부 파일 관련 로직 제거
- 댓글 Create 및 Update Unit Test 수정
=> [KIT-178] 첨부 파일 관련 로직 분리 / 댓글 Create 및 Update 수정

src/main/java/com/se/apiserver/v1/attach/application/dto/AttachReadDto.java, src/main/java/com/se/apiserver/v1/attach/application/service/AttachCreateService.java, src/main/java/com/se/apiserver/v1/multipartfile/application/dto/MultipartFileUploadDto.java, src/test/java/com/se/apiserver/v1/attach/application/service/AttachCreateServiceTest.java, src/test/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileUploadServiceTest.java
- Multipart upload 시 file size 추가
- 관련 서비스, 테스트 로직 수정
=> [KIT-194] Multipart File Size 속성 추가

src/main/java/com/se/apiserver/v1/common/infra/web/filter/CorsHeaderFilter.java
Cors 허용 목록에 https://localhost:3000 추가
=> [KIT-192] Cors 허용 목록에 https://localhost:3000 추가

src/main/java/com/se/apiserver/v1/reply/domain/entity/Reply.java
=> [KIT-198] 댓글 본문 글자수 제한 5000자로 수정.

src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java, src/test/java/com/se/apiserver/v1/post/application/service/PostAnnouncementServiceTest.java, src/test/java/com/se/apiserver/v1/post/application/service/PostReadServiceTest.java
게시판 내 게시글 목록 조회 시 boardID 대신 boardEngName으로 조회하도록 변경
=> [KIT-200] 게시판 내 게시글 목록 조회 시 boardID 대신 boardEngName으로 조회하도록 변경

src/main/java/com/se/apiserver/v1/common/infra/advice/SeExceptionAdvice.java
예외 처리 시 SeExceptionAdvice에서 제약조건 예외 처리하지 않도록 수정.
SE Exception Advice와 Global Controller Advice의 통합이 필요함.
=> [KIT-199] 예외 처리 시 SeExceptionAdvice에서 제약조건 예외 처리하지 않도록 수정.

src/main/java/com/se/apiserver/v1/post/application/dto/PostCreateDto.java, src/main/java/com/se/apiserver/v1/post/application/service/PostCreateService.java, src/test/java/com/se/apiserver/v1/post/application/service/PostCreateServiceTest.java
게시글 생성 시 boardId 대신 nameEng 사용하도록 변경
=> [KIT-200] 게시글 생성 시 boardId 대신 nameEng 사용하도록 변경

src/main/java/com/se/apiserver/v1/post/application/dto/PostReadDto.java, src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java, src/main/java/com/se/apiserver/v1/post/infra/repository/PostQueryRepositoryImpl.java, src/test/java/com/se/apiserver/v1/post/application/service/PostReadServiceTest.java
게시글 검색 시 boardId 대신 nameEng 사용하도록 변경
=> [KIT-200] 게시글 검색 시 boardId 대신 nameEng 사용하도록 변경

src/main/java/com/se/apiserver/v1/post/application/service/PostCreateService.java, src/main/java/com/se/apiserver/v1/post/domain/exception/NoticeSizeException.java, src/main/java/com/se/apiserver/v1/post/infra/api/PostApiController.java, src/test/java/com/se/apiserver/v1/post/application/service/PostCreateServiceTest.java
- yml 파일에 최대 공지 개수 설정
- Test 추가
=> [KIT-219] 공지 등록 시 등록된 공지 개수 체크

src/main/java/com/se/apiserver/v1/post/application/service/PostUpdateService.java, src/test/java/com/se/apiserver/v1/post/application/service/PostUpdateServiceTest.java
=> [KIT-219] 공지 수정 시 등록된 공지 개수 체크

src/main/java/com/se/apiserver/ApiserverApplication.java, src/main/java/com/se/apiserver/v1/blacklist/application/dto/BlacklistCreateDto.java, src/main/java/com/se/apiserver/v1/blacklist/application/dto/BlacklistReadDto.java, src/main/java/com/se/apiserver/v1/blacklist/application/error/BlacklistErrorCode.java, src/main/java/com/se/apiserver/v1/blacklist/application/service/BlacklistCreateService.java, src/main/java/com/se/apiserver/v1/blacklist/application/service/BlacklistDeleteService.java, src/main/java/com/se/apiserver/v1/blacklist/application/service/BlacklistDetailService.java, src/main/java/com/se/apiserver/v1/blacklist/application/service/BlacklistScheduleTask.java, src/main/java/com/se/apiserver/v1/blacklist/domain/entity/Blacklist.java, src/main/java/com/se/apiserver/v1/blacklist/infra/repository/BlacklistJpaRepository.java, src/main/java/com/se/apiserver/v1/blacklist/infra/schedule/BlacklistScheduleTask.java, src/main/java/com/se/apiserver/v1/common/infra/web/config/WebConfig.java, src/main/java/com/se/apiserver/v1/common/infra/web/interceptor/BlacklistInterceptor.java, src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistCreateServiceTest.java, src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistDeleteServiceTest.java, src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistDetailServiceTest.java, src/test/java/com/se/apiserver/v1/blacklist/application/service/BlacklistReadServiceTest.java, src/test/java/com/se/apiserver/v1/blacklist/domain/entity/BlacklistTest.java
- 사용자 블랙리스트화 추가
- 기존에는 ip만 블랙리스트화하였으나, 유저의idString(로그인아이디)를 사용해 블랙리스트에 등록 가능
- 요청(Request)방법 컨텍스트는 머지되면 추가하겠습니다.
- 1) ip, reason, releaseDate
- 2) idString, reason, releaseDate
- 모든 경우에서 releaseDate를 지정해주지 않으면 default값으로 ${spring.blacklist.release.default-plus-day}가 설정됩니다.
- 블랙리스트 종료날짜 추가
- releaseDate가 추가됨
- releaseDate가 지난 블랙리스트 객체들은 ${spring.blacklist.schedule.cron}값에 따라 Application에서 삭제가 실행됩니다.
- blacklist.infra내에 schedule 패키지 생성 후, BlacklistScheduleTask추가
- 정해진 시간적 루틴 마다 실행되어야하는 태스크들은 infra의 schedule패키지 내에서 관리합니다.
- 추가된 서비스로직에 따른 기존 Test code 수정됨
=> [KIT-207][KIT-208][KIT-210] 블랙리스트 고도화

build.gradle, src/main/java/com/se/apiserver/v1/common/infra/kafka/config/KafkaTemplateConfiguration.java, src/main/java/com/se/apiserver/v1/common/infra/kafka/config/ListenableFutureCallbackConfiguration.java
- gradle dependency 수정
- KafkaTemplate Config 추가
- Callback Config 추가
=> [KIT-173] Kafka Config 설정

src/main/java/com/se/apiserver/v1/mail/application/dto/MailSendDto.java, src/main/java/com/se/apiserver/v1/mail/application/service/MailSendService.java, src/main/java/com/se/apiserver/v1/mail/domain/producer/MailProducerProtocol.java, src/main/java/com/se/apiserver/v1/mail/presentation/producer/MailProducer.java
- Producer 추가
- Mail Send Service 추가
=> [KIT-173] Mail Producer 및 Service 추가

src/main/java/com/se/apiserver/v1/account/application/service/AccountFindPasswordService.java, src/main/java/com/se/apiserver/v1/account/application/service/AccountVerifyService.java, src/main/java/com/se/apiserver/v1/account/domain/entity/AccountVerifyToken.java, src/test/java/com/se/apiserver/v1/account/application/service/AccountFindPasswordServiceTest.java, src/test/java/com/se/apiserver/v1/account/application/service/AccountVerifyServiceTest.java
- 메일 송신과 관련된 일부 회원관리 서비스 수정
- 관련된 dto의 lombok 수정
=> [KIT-173] 회원관리 서비스 메일관련 로직 수정

src/main/resources/logback-spring.xml
로그 저장 경로 yml로 주입받도록 변경하였습니다.
클라우드에는 병합 완료 후 수정하겠습니다.
=> [KIT-227] 로그 저장 경로 yml로 주입받도록 변경

src/main/java/com/se/apiserver/v1/post/application/dto/PostReadDto.java, src/main/java/com/se/apiserver/v1/post/application/service/PostReadService.java, src/main/java/com/se/apiserver/v1/post/domain/entity/Post.java, src/main/java/com/se/apiserver/v1/post/domain/entity/PostContent.java, src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyReadDto.java, src/main/java/com/se/apiserver/v1/reply/domain/entity/Reply.java
- 비회원 게시글/댓글 조회 시 IP 함께 반환하도록 변경
- 게시글/댓글 제목, 내용의 길이 제약조건을 느슨하게 변경
=> [Kit-260] 비회원 게시글/댓글 조회 시 IP 함께 반환하도록 변경

src/main/java/com/se/apiserver/v1/account/application/service/QuestionReadService.java, src/main/java/com/se/apiserver/v1/account/infra/api/AccountApiController.java, src/test/java/com/se/apiserver/v1/account/application/service/QuestionReadServiceTest.java
- 사용자 ID를 입력으로 주면 회원가입때 저장한 질문을 조회하는 API 구현
=> [KIT-257] 사용자 ID로 질문 조회 API 구현

src/main/java/com/se/apiserver/v1/multipartfile/application/service/MultipartFileService.java
- 파일 업로드 시 생성할 다운로드 URL의 스키마를 주입받을 수 있도록 변경
- application.yml에 se-file-server.scheme 추가
=> [KIT-266] 파일 업로드 시 생성할 다운로드 URL의 스키마를 주입받을 수 있도록 변경

src/main/java/com/se/apiserver/v1/post/application/dto/PostReadDto.java, src/main/java/com/se/apiserver/v1/reply/application/dto/ReplyReadDto.java
- 게시글, 댓글 읽기 시 조회되는 IP는 절반만 표시되게 하였음.
ex) 256.123.456.789 -> 256.123
=> [KIT-262] 게시글, 댓글 읽기 시 조회되는 IP는 절반만 표시되게 하였음.
